# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
   name: hskim

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b8080774-4538-4d2c-b595-a005ffe98cef'
  imageRepository: 'app1/app1nginx'
  containerRegistry: 'acrdemokhs.azurecr.io'

  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

  tag: '$(Build.BuildId)'
  imagePullSecret: 'aksdevopsacr1755e8d5-auth'
  environment: 'Session-2'

  # Agent VM image name
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: kube-manifests
      artifact: kube-manifests


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy

    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: aksdemo1 - kubernetes
              manifests: |
                $(System.ArtifactsDirectory)/kube-manifests/Deployment.yml
                $(System.ArtifactsDirectory)/kube-manifests/02-buildpush-to-acr-deploy-to-aks.yml

              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
